[project]
org-name= "ballerinax"
version= "0.12.0"
authors = ["WSO2"]
repository = "https://github.com/ballerina-platform/module-gmail"
keywords = ["gmail","email"]
license = ["Apache-2.0"]

[dependencies]
