[package]
distribution = "2201.0.3"
org = "ballerinax"
name = "googleapis.gmail"
version = "3.0.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail"
keywords = ["Communication/Email", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
