name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      build --skip-tests
              env:
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }} 
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }} 
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  REFRESH_URL: ${{ secrets.REFRESH_URL }}
                  RECIPIENT: ${{ secrets.RECIPIENT }}
                  SENDER: ${{ secrets.SENDER }}
                  CC: ${{ secrets.CC }}
                  ATTACHMENT_PATH: ${{ secrets.ATTACHMENT_PATH }}
                  ATTACHMENT_CONTENT_TYPE: ${{ secrets.ATTACHMENT_CONTENT_TYPE }}
                  INLINE_IMAGE_PATH: ${{ secrets.INLINE_IMAGE_PATH }}
                  INLINE_IMAGE_NAME: ${{ secrets.INLINE_IMAGE_NAME }}
                  IMAGE_CONTENT_TYPE: ${{ secrets.IMAGE_CONTENT_TYPE }}
